name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/python@v1
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - uses: wtnb75/actions/wheel@v1
    - id: pdoc
      uses: wtnb75/actions/pdoc@v1
      with:
        output-dir: docs
        module: localpkg
        other-options: --docformat google
    - name: Install Task
      uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
    - shell: bash
      run: |
        uv sync --no-dev
        source .venv/bin/activate
        task prepare
        task APK_KEY=tmp.rsa pkg:apk:key
        task APK_KEY=tmp.rsa pkg:all
        task shutdown
        mkdir pkg
        mv *.deb *.rpm *.pkg.tar.zst *.apk *.tar.gz pkg/
    - name: pkg index
      run: |
        pip install dirindex
        dirindex make --template apache --hide index.html --recursive pkg
    - uses: wtnb75/actions/merge-pages@v1
      with:
        dirs: "cover docs pkg"
        #pydist: dist
    - uses: wtnb75/actions/docker@v1
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
